# docker compose --env-file docker-mysql.env up
version: '3.8'

networks:
  vue-project:
    external: false

services:
  # Kotlin Spring 模拟后端
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - docker-mysql.env
    environment:
      - DB_PORT=3306
    container_name: kotlin_spring_app
    networks:
      - vue-project
    depends_on:
      - db

  # Vue 前端项目
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue_frontend_app
    networks:
      - vue-project

  # MySQL 数据库
  db:
    image: mysql:latest
    container_name: mysql_db
    networks:
      - vue-project
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mysql-data:/var/lib/mysql

  # Nginx 服务器作为反向代理
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - vue-project
    depends_on:
      - backend
      - frontend
