spring:
  application:
    name: SimilarBackendForWebFrameworkHomework
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?${DB_PARAM}
    username: ${DB_USER}
    password: ${DB_PWD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
logging:
  level:
    dev:
      iceean: debug
    sql: debug